// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ_5Fp5NmOj56Fd5wADPUsKX61QKeAdAI',
    appId: '1:112874581164:web:98b763f5c544aa20c60309',
    messagingSenderId: '112874581164',
    projectId: 'agrikeep-19747',
    authDomain: 'agrikeep-19747.firebaseapp.com',
    storageBucket: 'agrikeep-19747.firebasestorage.app',
    measurementId: 'G-HM3ND1MP6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzwLDHHSN4iW3Zv8gQ80YYepc672ffNOU',
    appId: '1:112874581164:android:6a653c87431df766c60309',
    messagingSenderId: '112874581164',
    projectId: 'agrikeep-19747',
    storageBucket: 'agrikeep-19747.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeCMzQ8oR_8s2dbDrjnK95XR2ei367CmQ',
    appId: '1:112874581164:ios:663c3a4fe2aa3382c60309',
    messagingSenderId: '112874581164',
    projectId: 'agrikeep-19747',
    storageBucket: 'agrikeep-19747.firebasestorage.app',
    iosBundleId: 'com.example.myagrikeep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeCMzQ8oR_8s2dbDrjnK95XR2ei367CmQ',
    appId: '1:112874581164:ios:663c3a4fe2aa3382c60309',
    messagingSenderId: '112874581164',
    projectId: 'agrikeep-19747',
    storageBucket: 'agrikeep-19747.firebasestorage.app',
    iosBundleId: 'com.example.myagrikeep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ_5Fp5NmOj56Fd5wADPUsKX61QKeAdAI',
    appId: '1:112874581164:web:6190cf251ed85c4fc60309',
    messagingSenderId: '112874581164',
    projectId: 'agrikeep-19747',
    authDomain: 'agrikeep-19747.firebaseapp.com',
    storageBucket: 'agrikeep-19747.firebasestorage.app',
    measurementId: 'G-7WQ0NE7EZT',
  );
}
